### ISSUE TITLE
Make the tests in Chess.test.js pass

### ISSUE THREAD

**Issue by programarivm** [chesslablab/redux-chess#185]
At the present moment, two tests in `Chess.test.js` are not passing when running the following command:

```
$ npm test --detectOpenHandles -- Chess.test.js
```

Output:

```
 FAIL  src/__tests__/components/Chess.test.js
  Chess
    ✓ is rendered (427 ms)
    ✕ the first chess board square is a black rook before flipping the chess board (148 ms)
    ✕ the first chess board square is a white rook after flipping the chess board (233 ms)
    ✓ opens the 'Invite a friend' dialog (341 ms)

  ● Chess › the first chess board square is a black rook before flipping the chess board

    expect(received).toEqual(expected) // deep equality

    Expected: "♜"
    Received: ""

      43 |     const text = chess.find('.board-row').at(0).find('.square').at(0).find('span').text();
      44 |     expect(store.getState().board.flip).toBe('w');
    > 45 |     expect(text).toEqual('♜');
         |                  ^
      46 |   });
      47 |   it("the first chess board square is a white rook after flipping the chess board", () => {
      48 |     const action = { type: boardActionTypes.FLIP };

      at Object.<anonymous> (src/__tests__/components/Chess.test.js:45:18)

  ● Chess › the first chess board square is a white rook after flipping the chess board

    expect(received).toEqual(expected) // deep equality

    Expected: "♖"
    Received: ""

      51 |     const text = chess.find('.board-row').at(0).find('.square').at(0).find('span').text();
      52 |     expect(result.current.state.board.flip).toBe('b');
    > 53 |     expect(text).toEqual('♖');
         |                  ^
      54 |   });
      55 |   it("opens the 'Invite a friend' dialog", () => {
      56 |     const action = { type: createInviteCodeDialogActions.OPEN };

      at Object.<anonymous> (src/__tests__/components/Chess.test.js:53:18)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 passed, 4 total
Snapshots:   0 total
Time:        5.289 s
Ran all test suites matching /Chess.test.js/i.

Active Filters: filename /Chess.test.js/
 › Press c to clear filters.

Watch Usage
 › Press a to run all tests.
 › Press f to run only failed tests.
 › Press o to only run tests related to changed files.
 › Press q to quit watch mode.
 › Press p to filter by a filename regex pattern.
 › Press t to filter by a test name regex pattern.
 › Press Enter to trigger a test run.
```

However, all tests were passing a few days ago; thus, this issue is intended to review what could be wrong and make the tests pass.

Happy coding and learning!

**Comment by programarivm** [comment]
Attached below is the output obtained after closing https://github.com/chesslablab/redux-chess/issues/184

```
PASS  src/__tests__/utils/Piece.test.js
 PASS  src/__tests__/utils/Ascii.test.js
 PASS  src/__tests__/utils/Wording.test.js
 PASS  src/__tests__/utils/Opening.test.js
 PASS  src/__tests__/utils/Movetext.test.js
 FAIL  src/__tests__/components/Chess.test.js
  ● Chess › the first chess board square is a black rook before flipping the chess board

    Method “text” is meant to be run on 1 node. 0 found instead.

      42 |   it("the first chess board square is a black rook before flipping the chess board", () => {
      43 |     const chess = mount(<Chess props={props} />);
    > 44 |     const text = chess.find('.board').at(0).find('.square').at(0).find('span').text();
         |                                                                                ^
      45 |     expect(store.getState().board.flip).toBe('w');
      46 |     expect(text).toEqual('♜');
      47 |   });

      at ReactWrapper.single (node_modules/enzyme/src/ReactWrapper.js:1168:13)
      at ReactWrapper.text (node_modules/enzyme/src/ReactWrapper.js:629:17)
      at Object.<anonymous> (src/__tests__/components/Chess.test.js:44:80)

  ● Chess › the first chess board square is a white rook after flipping the chess board

    Method “text” is meant to be run on 1 node. 0 found instead.

      50 |     const { result } = renderHook(() => SyncDispatcher(action), { wrapper });
      51 |     const chess = mount(<Chess props={props} />);
    > 52 |     const text = chess.find('.board-row').at(0).find('.square').at(0).find('span').text();
         |                                                                                    ^
      53 |     expect(result.current.state.board.flip).toBe('b');
      54 |     expect(text).toEqual('♖');
      55 |   });

      at ReactWrapper.single (node_modules/enzyme/src/ReactWrapper.js:1168:13)
      at ReactWrapper.text (node_modules/enzyme/src/ReactWrapper.js:629:17)
      at Object.<anonymous> (src/__tests__/components/Chess.test.js:52:84)

Test Suites: 1 failed, 5 passed, 6 total
Tests:       2 failed, 48 passed, 50 total
Snapshots:   0 total
Time:        7.382 s
Ran all test suites.

Watch Usage: Press w to show more.
```
Keep it up, and happy learning and coding.

**Comment by EndBug** [comment]
Hi, I'd like to open a PR for this issue in the next days, could you assign this to me? Thanks :)
